export const teamMembers = [
  {
    id: "1",
    name: "Sarah Chen",
    role: "Head IT Prefect",
    email: "sarah.chen@school.edu",
    phone: "ext. 1234",
    avatar: "/professional-woman-diverse.png",
    status: "ADMIN",
    specialties: ["Network Management", "Security"],
    department: "IT Leadership",
    isActive: true,
    lastLoginAt: "2025-09-19T10:00:00Z",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    role: "Deputy Head",
    email: "marcus.johnson@school.edu",
    phone: "ext. 1235",
    avatar: "/professional-man.png",
    status: "ADMIN",
    specialties: ["Hardware Support", "Training"],
    department: "IT Leadership",
    isActive: true,
    lastLoginAt: "2025-09-19T09:45:00Z",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    role: "Senior Prefect",
    email: "emily.rodriguez@school.edu",
    phone: "ext. 1236",
    avatar: "/professional-woman-tech.png",
    status: "HELPER",
    specialties: ["Software Support", "Documentation"],
    department: "Support",
    isActive: true,
    lastLoginAt: "2025-09-18T15:30:00Z",
  },
  {
    id: "4",
    name: "David Kim",
    role: "Senior Prefect",
    email: "david.kim@school.edu",
    phone: "ext. 1237",
    avatar: "/professional-man-tech.png",
    status: "HELPER",
    specialties: ["Database Management", "Web Development"],
    department: "Development",
    isActive: true,
    lastLoginAt: "2025-09-18T14:00:00Z",
  },
  {
    id: "5",
    name: "Alex Thompson",
    role: "Junior Prefect",
    email: "alex.thompson@school.edu",
    phone: "ext. 1238",
    avatar: "/young-professional.png",
    status: "GUEST",
    specialties: ["User Support", "Mobile Devices"],
    department: "Support",
    isActive: false,
    lastLoginAt: "2025-09-17T11:20:00Z",
  },
]
